name: Deploy para GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Uploadar artefatos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Altere se seu conteúdo estiver em outra pasta

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
